version: "3"
services:
  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    env_file: .env
    restart: unless-stopped
    volumes:
      - influxdb_data:/var/lib/influxdb
    #  - ./influxdb/conf/influxdb.conf:/etc/influxdb/influxdb.conf:ro
    ports:
      - "8086:8086"

  grafana:
    image: grafana/grafana-oss
    container_name: grafana-oss
    env_file: .env
    restart: unless-stopped
    volumes:
      - grafana_data:/var/lib/grafana
      #- ./grafana/conf/grafana.ini:/etc/grafana/grafana.ini:ro
      - ./grafana/provisioning/:/etc/grafana/provisioning
      - ./grafana/dashboardImport/:/var/lib/grafana/dashboards:ro
    ports:
      - 3000:3000
    links:
      - influxdb
    depends_on:
      - influxdb

  speedflux:
    container_name: speedflux
    restart: unless-stopped
    build: .
    env_file: .env
    image: speedflux
    links:
      - influxdb
    depends_on:
      - influxdb

volumes:
  influxdb_data:
  grafana_data:
